export const URLS = {
  LOGIN: "login",
  SUGGESTION:"suggestion",
  DASHBOARD: "dashboard",
  INVITEDJOBS:"invitedJobs",
  JOBDETAILS: "jobdetails",
  JOBDETAILSPUBLIC: "jobdetailspublic",
  JOBSEARCH: "jobsearch",
  USERPROFILE: "userprofile",
  CREATEJOB: "createjob",
  UPDATEPASSWORD: "updatePassword",
  LANDINGRECRUITER: "landingRecruiter",
  LANDINGCOUNSELLOR:"landingCounsellor",
  SEARCHJOBS: "searchJobs",
  SEARCHJOBSHOME: "searchJobsHome",
  AUTHENTICATION:"authentication",
  FORGOTPASSWORD:"forgotPassword",
  VERIYFORGOTPASSWORD:"verifyForgotPassword",
  SCREENINGPAGE: "screeningPage",
  EDITJOB: "editjob",
  APPLIEDJOBLIST: "appliedjoblist",
  LOGIN:"login",
  SIGNUP:"signup",
  COMPANYMANAGE:"companymanage",
  RECRUITERMANGE:"recruitermanage",
  COMPANYFORM:"companyform",
  EDITCOMPANY:"editcompany",
  VIEWCOMPANY:"viewcompany"
};
